Update 搭建节点的一个方式

diff --git a/搭建节点的一个方式 b/搭建节点的一个方式
--- a/搭建节点的一个方式
+++ b/搭建节点的一个方式
@@ -1,11 +1,3 @@
-准备工作：
-
-一台vps带公网IP，ubuntu 18.04+ 即可，root用户
-
-一个解析到你vps公网IP的域名【如 vmess.v2ray.one】
-
-第一部分 [ 手动配置v2ray ]
-
 # 配置系统时区为东八区
 
 rm -f /etc/localtime
@@ -41,6 +33,38 @@ ssl_dir="$(mkdir -pv "/usr/local/etc/v2ray/ssl/`date +"%F-%H-%M-%S"`" |awk -F"'"
 #6.定义nginx和v2ray配置文件路径
 nginxConfig="/etc/nginx/conf.d/v2ray.conf"
 v2rayConfig="/usr/local/etc/v2ray/config.json"
+# 检测域名解析是否正确
+
+#域名解析正确不会输出任何内容，如果不正确会退出当前终端
+local_ip="$(curl ifconfig.me 2>/dev/null;echo)"
+resolve_ip="$(host "$domainName" | awk '{print $NF}')"
+if [ "$local_ip" != "$resolve_ip" ];then echo "域名解析不正确";exit 9;fi
+# 使用v2ray官方命令安装v2ray，并设置开机启动
+
+curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
+curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh
+bash install-release.sh
+bash install-dat-release.sh
+systemctl enable v2ray
+# 修正官方5.1+版本安装脚本启动命令错误
+grep -r 'v2ray -config' /etc/systemd/system/* | cut -d: -f1 | xargs -i sed -i 's/v2ray -config/v2ray run -config/' {}
+systemctl daemon-reload
+# 安装acme,并申请加密证书
+
+#会提示安装socat，这里使用alpn模式，不用理会
+
+source ~/.bashrc
+if nc -z localhost 443;then /etc/init.d/nginx stop;fi
+if nc -z localhost 443;then lsof -i :443 | awk 'NR==2{print $1}' | xargs -i killall {};sleep 1;fi
+if ! [ -d /root/.acme.sh ];then curl https://get.acme.sh | sh;fi
+~/.acme.sh/acme.sh --set-default-ca --server letsencrypt
+~/.acme.sh/acme.sh --issue -d "$domainName" -k ec-256 --alpn
+~/.acme.sh/acme.sh --installcert -d "$domainName" --fullchainpath $ssl_dir/v2ray.crt --keypath $ssl_dir/v2ray.key --ecc
+chown www-data.www-data $ssl_dir/v2ray.*
+# 把续签证书命令添加到计划任务
+
+echo -n '#!/bin/bash
+/etc/init.d/nginx stop
 wait;"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" &> /root/renew_ssl.log
 wait;/etc/init.d/nginx start
 ' > /usr/local/bin/ssl_renew.sh
@@ -78,6 +102,69 @@ server {
 
 }
 " > $nginxConfig
+# 配置v2ray，执行如下命令即可添加v2ray配置文件
+
+echo '
+{
+  "log" : {
+    "access": "/var/log/v2ray/access.log",
+    "error": "/var/log/v2ray/error.log",
+    "loglevel": "warning"
+  },
+  "inbound": {
+    "port": '$port',
+    "listen": "127.0.0.1",
+    "protocol": "vmess",
+    "settings": {
+      "decryption":"none",
+      "clients": [
+        {
+          "id": '"\"$uuid\""',
+          "level": 1
+        }
+      ]
+    },
+   "streamSettings":{
+      "network": "ws",
+      "wsSettings": {
+           "path": '"\"$path\""'
+      }
+   }
+  },
+  "outbound": {
+    "protocol": "freedom",
+    "settings": {
+      "decryption":"none"
+    }
+  },
+  "outboundDetour": [
+    {
+      "protocol": "blackhole",
+      "settings": {
+        "decryption":"none"
+      },
+      "tag": "blocked"
+    }
+  ],
+  "routing": {
+    "strategy": "rules",
+    "settings": {
+      "decryption":"none",
+      "rules": [
+        {
+          "type": "field",
+          "ip": [ "geoip:private" ],
+          "outboundTag": "blocked"
+        }
+      ]
+    }
+  }
+}
+' > $v2rayConfig
+
+# 默认配置vmess协议，如果指定vless协议则配置vless协议
+[ "vless" = "$2" ] && sed -i 's/vmess/vless/' $v2rayConfig
+# 完工，你现在只需要重启v2ray和nginx即可
 
 systemctl restart v2ray
 systemctl status -l v2ray
@@ -91,4 +178,3 @@ echo "UUID: $uuid"
 echo "安全: tls"
 echo "传输: websocket"
 echo "路径: $path"
-# 注：为适应v2ray-core目前和未来的版本更新，vmess协议额外ID选项已移除，客户端vmess协议额外id配置为0即可，当前最新版v2rayN客户端已默认为0
